loan = float(input("Enter the amount of loan : "))
roi = float(input("Enter rate of intrest : "))
print("How you want to pay the loan : ")
print("1. Monthly\n2. Weekly\n3. Daily\n4. Continually")
ch = int(input("Enter your choice : "))
